/* empty css                      */(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function u(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=u(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const l=document.querySelector(".menu-button"),s=l.querySelector(".icon"),u=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const c=`
<svg width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M34 30L10 30" stroke="#15171C" stroke-width="2" stroke-linecap="round" />
  <path d="M34 22L10 22" stroke="#15171C" stroke-width="2" stroke-linecap="round" />
  <path d="M34 14L10 14" stroke="#15171C" stroke-width="2" stroke-linecap="round" />
</svg>
    `,o=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#15171C" />
</svg>
    `;l.addEventListener("click",()=>{t=!t,s.innerHTML=t?o:c,t?n():r()}),d.forEach(a=>a.addEventListener("click",()=>{r(),s.innerHTML=c,t=!1})),window.addEventListener("scroll",i);function n(){u.style.display="block"}function r(){u.style.display="none"}function i(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function l(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function s(o){const n=document.getElementById(o);if(!n)return;const r=l(),i=n.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:i,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(n){const r=this.getAttribute("href");if(!r)return;const[i,a]=r.split("#");if(!a)return;const f=window.location.pathname.split("/").pop();!(i===""||i==="./"||i===f||i==="./"+f)||!document.getElementById(a)||(n.preventDefault(),s(a),t(a))})});const d=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(r=>r.classList.remove("active"));const n=document.querySelector(`.navigation-item a[href*="#${o}"]`);n&&n.closest(".navigation-item").classList.add("active")}function c(){const o=window.pageYOffset+l()+100;d.forEach(n=>{const r=n.offsetTop,i=r+n.offsetHeight;o>=r&&o<i&&t(n.id)})}if(window.addEventListener("scroll",c),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{s(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
